cocom_site/cocom_site/urls.py
#from django.conf.urls.defaults import *  # changed for django 1.6
from django.conf.urls import patterns, url, include
from django.views.generic.base import RedirectView
from django.conf import settings
from satchmo_store.urls import basepatterns
from django.conf.urls.i18n import i18n_patterns
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.contrib import admin
admin.autodiscover()

from dajaxice.core import dajaxice_autodiscover, dajaxice_config
dajaxice_autodiscover()

#import reportengine
#reportengine.autodiscover()

# For redirects
#from django.views.generic.simple import redirect_to


# For django rest
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets

'''
# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ('url', 'username', 'email', 'is_staff')

# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
'''
urlpatterns = []

try:
    from local_urls import *
except ImportError:
    print "no local_urls"

urlpatterns = patterns('',
    # dajaxice
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),

    # Language free versions of the satchmo urls (This might not be necessary.)
    url(r'^shop/', include('satchmo_store.shop.urls')),

    # TODO Fix Satchmo URLS
    # Catch the old satchmo urls and forward them to shop/
    # (in case people have bookmarked pages)
    url('^product/(?P<slug>[a-zA-Z0-9_-]+)/$', RedirectView.as_view(url= '/shop/product/%(slug)s/')),
    url('^category/(?P<slug>[a-zA-Z0-9_-]+)/$',RedirectView.as_view(url= '/shop/category/%(slug)s/')),
    url('^cart/(?P<slug>[a-zA-Z0-9_-]+)/$',    RedirectView.as_view(url= '/shop/cart/%(slug)s/')),

    url(r'^jsi18n/(?P<packages>\S+?)/$', 'django.views.i18n.javascript_catalog'),
    #Form desiner form path for if a form is not on a cms page
    url(r'^forms/', include('form_designer.urls')),
    # TODO reportengine project doens't support django 1.6 and is discontinued.
    #url(r'^reports/', include('reportengine.urls')),
    # fix to stop having 404 due to missing favicon... renders black favicon

    # TODO Fix favicon view
    url(r'^favicon\.ico$', RedirectView.as_view(url=  '/static/images/favicon.ico')),
) + urlpatterns

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = patterns('',
    # redirects to static media files (css, javascript, images, etc.)
    url(r'^__debug__/', include(debug_toolbar.urls)),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',  {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    url(r'', include('django.contrib.staticfiles.urls')),
) + urlpatterns

urlpatterns += basepatterns + i18n_patterns('',
    # TODO Fix Satchmo URLS
    # Catch the old satchmo urls and forward them to shop/ (International Version)
    # (in case people have bookmarked pages)
    url('^product/(?P<slug>[a-zA-Z0-9_-]+)/$', RedirectView.as_view(url= '/shop/product/%(slug)s/')),
    url('^category/(?P<slug>[a-zA-Z0-9_-]+)/$',RedirectView.as_view(url= '/shop/category/%(slug)s/')),
    url('^cart/(?P<slug>[a-zA-Z0-9_-]+)/$',    RedirectView.as_view(url= '/shop/cart/%(slug)s/')),

    # admin pages
    url(r'^admin/', include(admin.site.urls)),
    # The language switcher sometimes prepends "p/" to the url. This catches these. Why does it do that??? 
    url(r'^p/', include('satchmo_store.shop.urls')),
    # Language enabled versions of the satchmo urls. 
    url(r'^shop/', include('satchmo_store.shop.urls')),
    # Language enabled versions of the django cms urls.
    url(r'^', include('cms.urls')),
    )

urlpatterns += staticfiles_urlpatterns()

cocom_site/cocom_seo/models.py
from django.db import models

# To make Django CMS plugins
from cms.models.pluginmodel import CMSPlugin

class SEOModel(CMSPlugin):

    description = models.TextField(blank=True)
    keywords = models.TextField(blank=True)

    def __unicode__(self):
        return self.description

cocom_site/templates/contact/_addressblock.html
{# output an address as a textblock #}
{% load i18n %}
<ul class="addressblock">
{% if address.addressee %}
    <li>{{address.addressee}}</li>
{% endif %}
{% if address %}
    <li>{{ address.street1 }}</li>
    {% if address.street2 %}<li>{{ address.street2 }}</li>{% endif %}
    <li>{{ address.city }}{% if address.state %}, {{ address.state }}{% endif %}</li>
    {% if address.postal_code %}<li>{{ address.postal_code }}</li>{% endif %}
    <li>{{ address.country }}</li>
{% else %}
    <li>{% trans 'Not set' %}</li>
{% endif %}
</ul>

cocom_site/templates/contact/_contact_info_form.html
{# This template is meant to be used by ContactInfoForm and it's subclasses. #}

{% block contact-form-imports %}
{% include "shop/_jquery.html" %}
{% include "shop/_jquery_form.html" %}

{% if shop.options.PAYMENT.COUNTRY_MATCH.value %}
{% include "contact/_country_match_script.html" %}
{% endif %}
{% include "contact/_contact_info_form_js.html" %}
{% include "contact/_state_js.html" %}
{% endblock %}

cocom_site/templates/contact/_contact_info_form_billing.html
{% load i18n %}

{% block billing-info %}
    <tr><td colspan="2"><h4>{% trans "Billing Information" %}</h4></td></tr>

    <tr><td><label for="id_addressee">{% trans "Bill To" %}</label><p class="help">{% trans "If different from the first and last names above" %}</p></td><td> {{ form.addressee }}</td></tr>
    {% if form.addressee.errors %}<tr><td class="error" colspan="2">*** {{ form.addressee.errors|join:", "}}</td></tr>{% endif %}

    <tr><td><label for="id_street1">{% trans "Street" %}{% if form.street1.field.required %}*{% endif %}</label></td><td> {{ form.street1 }}</td></tr>
    {% if form.street1.errors %}<tr><td class="error" colspan="2">*** {{ form.street1.errors|join:", " }}</td></tr>{% endif %}

    <tr><td><label for="id_street2">{% trans "Street" %}</label></td><td> {{ form.street2 }}</td></tr>
    {% if form.street2.errors %}<tr><td class="error" colspan="2">*** {{ form.street2.errors|join:", " }}</td></tr>{% endif %}

    <tr><td><label for="id_city">{% trans "City" %}{% if form.city.field.required %}*{% endif %}</label></td><td> {{ form.city }}</td></tr>
    {% if form.city.errors %}<tr><td class="error" colspan="2">*** {{ form.city.errors|join:", " }}</td></tr>{% endif %}

    {% if country %}
      {% if form.fields.state.choices %}
      <tr>
        <td><label for="id_state">{% if country.get_admin_area_display %}{{ country.get_admin_area_display }}{% else %}{% trans "State/Province" %}{% endif %} {% if form.state.field.required %}*{% endif %}</label></td>
        <td><p id="id_state_loading" style="display: none">Loading...</p> {{ form.state }}</td>
      </tr>
      {% endif %}
    {% else %}
      <tr>
        <td><label for="id_state">{% trans "State/Province" %} {% if form.state.field.required %}*{% endif %}</label></td>
        <td><p id="id_state_loading" style="display: none">Loading...</p> {{ form.state }}</td>
      </tr>
    {% endif %}
    {% if form.state.errors %}<tr><td class="error" colspan="2">*** {{ form.state.errors|join:", " }}</td></tr>{% endif %}

    <tr><td><label for="id_postal_code">{% trans "Zipcode/Postcode" %}{% if form.postal_code.field.required %}*{% endif %}</label></td><td> {{ form.postal_code }}</td></tr>
    {% if form.postal_code.errors %}<tr><td class="error" colspan="2">*** {{ form.postal_code.errors|join:", " }}</td></tr>{% endif %}

    {% if not country %}
    <tr><td><label for="id_country">{% trans "Country" %}</label></td><td> {{ form.country }}</td></tr>
    {% if form.country.errors %}<tr><td class="error" colspan="2">*** {{ form.country.errors|join:", " }}</td></tr>{% endif %}
    {% endif %}
{% endblock %}

cocom_site/templates/contact/_contact_info_form_js.html
<script type="text/javascript">
var satchmo = satchmo || {};

satchmo.ship_form_toggler = function(state) {
    var inputs = $('tr.shiprow input');
    inputs.attr('disabled', state);
    var selects = $('tr.shiprow select');
    selects.attr('disabled', state);
    var rows = $('tr.shiprow');
    if (state) {
        rows.addClass('disabled');
        inputs.each(function() {
            $(this)[0].value = "";
        });
        selects.each(function() {
            $(this)[0].value = "";
        });
    } else {
        rows.removeClass('disabled');
    }
};

satchmo.update_ship_copy = function(elt) {
    var state = $(elt)[0].checked;
    satchmo.ship_form_toggler(state);
};

$(document).ready(function() {
    var copy_address = $('#id_copy_address');

    {# If copy address is missing, it's a cart which isn't shippable #}
    if (copy_address.length) {
        satchmo.update_ship_copy('#id_copy_address');
        $('#id_copy_address').click(function() {
            satchmo.update_ship_copy(this);
        });
    }
});

satchmo.name_change = function() {
    var first_name = $('#id_first_name').attr('value');
    var last_name = $('#id_last_name').attr('value');
    var old_first_name = $('#id_first_name').data('old_first_name');
    var old_last_name = $('#id_last_name').data('old_last_name');
    var full_name = $.trim(first_name + ' ' + last_name);
    var old_full_name = $.trim(old_first_name + ' ' + old_last_name);
    if ($('#id_addressee').attr('value') === old_full_name) {
    $('#id_addressee').attr('value', full_name);
    }
    if ($('#id_ship_addressee').attr('value') === old_full_name) {
    $('#id_ship_addressee').attr('value', full_name);
    }
    $('#id_first_name').data('old_first_name', first_name);
    $('#id_last_name').data('old_last_name', last_name);
};

$(document).ready(function() {
    satchmo.name_change();
    $('#id_first_name').bind("change", {}, satchmo.name_change);
    $('#id_last_name').bind("change", {}, satchmo.name_change);
});
</script>

cocom_site/templates/contact/_contact_info_form_shipping.html
{% load i18n %}

{% block shipping-info %}
    <tr><td colspan="2"><h4>{% trans "Shipping Information" %}</h4></td></tr>

    <tr><td><label for="id_copy_address">{% trans "Shipping same as billing?" %}</label></td><td> {{ form.copy_address }}</td></tr>
    {% if form.copy_address.errors %}<tr><td class="error" colspan="2">*** {{ form.copy_address.errors|join:", " }}</td></tr>{% endif %}

    <tr><td><label for="id_ship_addressee">{% trans "Ship To" %}</label><p class="help">{% trans "If different from the first and last names above" %}</td><td> {{ form.ship_addressee }}</td></tr>
    {% if form.ship_addressee.errors %}<tr><td class="error" colspan="2">*** {{ form.ship_addressee.errors|join:", "}}</td></tr>{% endif %}

    <tr class="shiprow"><td><label for="id_ship_street1">{% trans "Street" %} {% if form.ship_street1.field.required %}*{% endif %}</label></td><td> {{ form.ship_street1 }}</td></tr>
    {% if form.ship_street1.errors %}<tr><td class="error" colspan="2">*** {{ form.ship_street1.errors|join:", " }}</td></tr>{% endif %}

    <tr class="shiprow"><td><label for="id_ship_street2">{% trans "Street" %} {% if form.ship_street2.field.required %}*{%endif%}</label></td><td> {{ form.ship_street2 }}</td></tr>
    {% if form.ship_street2.errors %}<tr><td class="error" colspan="2">*** {{ form.ship_street2.errors|join:", " }}</td></tr>{% endif %}

    <tr class="shiprow"><td><label for="id_ship_city">{% trans "City" %} {% if form.ship_city.field.required %}*{% endif %}</label></td><td> {{ form.ship_city }}</td></tr>
    {% if form.ship_city.errors %}<tr><td class="error" colspan="2">*** {{ form.ship_city.errors|join:", " }}</td></tr>{% endif %}

    {% if country %}
      {% if form.fields.ship_state.choices %}
       <tr class="shiprow">
         <td><label for="id_ship_state">{% if country.get_admin_area_display %}{{ country.get_admin_area_display }}{% else %}{% trans "State/Province" %}{% endif %} {% if form.ship_state.field.required %}*{% endif %}</label></td>
         <td><p id="id_ship_state_loading" style="display: none">Loading...</p> {{ form.ship_state }}</td>
       </tr>
      {% endif %}
    {% else %}
      <tr class="shiprow">
        <td><label for="id_ship_state">{% trans "State/Province" %} {% if form.ship_state.field.required %}*{% endif %}</label></td>
        <td><p id="id_ship_state_loading" style="display: none">Loading...</p> {{ form.ship_state }}</td>
      </tr>
    {% endif %}
    {% if form.ship_state.errors %}<tr><td class="error" colspan="2">*** {{ form.ship_state.errors|join:", " }}</td></tr>{% endif %}

    <tr class="shiprow"><td><label for="id_ship_postal_code">{% trans "Zipcode/Postcode" %} {% if form.ship_postal_code.field.required %}*{% endif %}</label></td><td>{{ form.ship_postal_code }}</td></tr>
    {% if form.ship_postal_code.errors %}<tr><td class="error" colspan="2">*** {{ form.ship_postal_code.errors|join:", " }}</td></tr>{% endif %}

    {% if not country %}
    <tr class="shiprow"><td><label for="id_ship_country">{% trans "Country" %} {% if form.ship_country.field.required %}*{% endif %}</label></td><td> {{ form.ship_country }}</td></tr>
    {% if form.ship_country.errors %}<tr><td class="error" colspan="2">*** {{ form.ship_country.errors|join:", " }}</td></tr>{% endif %}
    {% endif %}
{% endblock %}

cocom_site/templates/contact/_country_match_script.html
<script type="text/javascript">
var satchmo = satchmo || {};

satchmo.updating = false;

satchmo.force_match = function(elt, ship) {
    
    var val = $(elt).val();
    if (!satchmo.updating) {
        satchmo.updating = true;
        if (ship) {
            $('#id_country').attr('value', val);
        } else {
            $('#id_ship_country').attr('value', val);
        }
        satchmo.updating = false;
    }
};

$(function() {
    satchmo.force_match($('#id_country'), false);
    $('#id_country').change(function() { satchmo.force_match(this, false) });
    $('#id_ship_country').change(function() { satchmo.force_match(this, true) });
});
</script>

cocom_site/templates/contact/_login_form.html
{% load i18n %}

{% block login-form %}
<form name="loginform" method="post" action="{% url "auth_login" %}">{% csrf_token %}
<input type="hidden" name="next" value="{% if next %}{{ next }}{% else %}{% url "satchmo_account_info" %}{% endif %}" />
<input type="hidden" name="action" value="login" />
<table class="form" style="float:left; width: 50%">
    <thead>
        <tr>
            <th colspan="2" class="label"><b>{% trans 'Existing members login' %}</b></th>
        </tr>
    </thead>
    <tbody>
        {% if loginform.non_field_errors %}
            <tr><td class="warn" colspan="2">
				{{ loginform.non_field_errors }}
            </td></tr>
        {% endif %}
        <tr>
            <td class="label">
                <label for="id_username">{% trans "Email Address:" %}</label>
            </td>
            <td class="text">
                {{loginform.username }}
            </td>
        </tr>
        {% if loginform.username.errors %}<tr><td colspan="2">{{ loginform.username.errors|join:", " }}</td></tr>{% endif %}
        <tr>
            <td class="label">
                <label for="id_password">{% trans "Password:" %}</label>
            </td>
            <td class="text">
                {{loginform.password }}
            </td>
        </tr>
        {% if loginform.password.errors %}<tr><td colspan="2">{{ loginform.password.errors|join:", " }}</td></tr>{% endif %}
        <tr>
            <td colspan="2" class="button">
				<input type="submit" name="login" value="{% trans 'Login' %}" />
            </td>
        </tr>
    </tbody>
</table>
</form>
{% endblock %}

cocom_site/templates/contact/_state_choices.html
{# Used to populate the dropdown state field via ajax. #}
{% for area in areas %}
	<option value="{{area.0}}"{% if forloop.first %} selected="selected"{% endif %}>{{area.1}}</option>
{% endfor %}

cocom_site/templates/contact/_state_js.html
{% if shop.options.SHOP.ENFORCE_STATE.value %}
<script type="text/javascript">
/**
 * Populates state fields when the user selects a country.
 *
 * The following callbacks are provided and can be overriden. They are called
 *  - when a request for values for the state field is sent,
 *  - and when a response is received (regardless of success or error).
 *
 *  - satchmo.on_state_load(state)
 *  - satchmo.on_ship_state_load(state)
 *
 * where state is a Boolean value:
 *  - true, when the request is sent;
 *  - false, when a response is received.
 */
jQuery(document).ready(function($) {
	var satchmo = satchmo || {};

	/* should choices for billing state be the same as those for shipping state? (and vice-versa) */
	var CLONE = {% if shop.options.PAYMENT.COUNTRY_MATCH.value %}true{% else %}false{% endif %};

	var hook_country_field = function(params) {
		params.country.change(function() {
			var data = {};
			data[params.data_key] = $(this).val();

			var success = function(result) {
				if (!result) { return; }
				params.state.html(result);
				satchmo[params.state_callback](false);

				if (!CLONE) { return; }
				params.other_state.html(result);
				satchmo[params.other_state_callback](false);
			};

			var error = function() {
				satchmo[params.state_callback](false);
				if (CLONE) { satchmo[params.other_state_callback](false); }
			};

			/* invoke callback for this field... */
			satchmo[params.state_callback](true);
			/* and its complement */
			if (CLONE) { satchmo[params.other_state_callback](true); }

			$.ajax({
				type: "POST",
				url: "{% url "satchmo_contact_ajax_state" %}",
				data: data,
				success: success,
				error: error,
				dataType: "html"
			});
		});
	};

	/* try and separate assumptions about the DOM. */
	var init_for_prefix = function(prefix) {
		var other_prefix;

		if (prefix == "") { other_prefix = "ship_"; }
		else if (prefix == "ship_") { other_prefix = ""; }
		else { return; }

		var params = {
			country: $(":input[name="+prefix+"country]"),
			state: $(":input[name="+prefix+"state]"),
			state_callback: prefix+"state_load",
			other_state: $(":input[name="+other_prefix+"state]"),
			other_state_callback: other_prefix+"state_load",
			data_key: prefix+"country"
		};

		/* Provide default loading handlers. */
		satchmo[params.state_callback] = function(state) {
			if (state) {
				$("#id_"+prefix+"state_loading").show();
				params.country.attr("disabled", true);
				params.state.attr("disabled", true);
			} else {
				$("#id_"+prefix+"state_loading").hide();
				params.country.attr("disabled", false);
				params.state.attr("disabled", false);
			}
		};

		/* Hook up country fields. */
		hook_country_field(params);
	};

	var field_prefixes = ["", "ship_"];
	for (var i in field_prefixes) {
		init_for_prefix(field_prefixes[i]);
	}
});

/**
* Required for Django's CSRF protection when using AJAX
* Taken from here - http://docs.djangoproject.com/en/dev/ref/contrib/csrf/
 */

$('html').ajaxSend(function(event, xhr, settings) {
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie != '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) == (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
        // Only send the token to relative URLs i.e. locally.
        xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
    }
});

</script>
{% endif %}

cocom_site/templates/contact/address_form.html
{% extends "shop/base.html" %}
{% load i18n %}

{% block extra-head %}
{% include "contact/_contact_info_form.html" %}
{% endblock %}

{% block navbar %}
   <li class="first"><a href="{{ shop_base }}/">{% trans "Home" %}</a></li>
   <li><a href="{% url "satchmo_account_info" %}">{% trans "Account" %}</a></li>
   <li>{% trans "Add Address" %}</li>
{% endblock %}


{% block content %}
{% if editing %}
    <h4>{% trans "Edit address book entry" %}</h4>
{% else %}
    <h4>{% trans "Add address to your address book" %}</h4>
{% endif %}
{% if form.non_field_errors %}
<h2>{% trans "Please correct the following error:" %}</h2>
{{ form.non_field_errors }}
{% endif %}

{% if editing %}
<form method="post" action="{% url "satchmo_address_edit" entry.id %}{% if next %}?next={{next}}{% endif%}">{% csrf_token %}
{% else %}
<form method="post" action="{% url "satchmo_address_create" %}{% if next %}?next={{next}}{% endif%}">{% csrf_token %}
{% endif %}
<table>
    <tr><td colspan="2"><p>{% trans "You&apos;ll need to fill out at least the fields with a *" %}</p></td></tr>

	<tr><td colspan="2"><h4>{% trans "Address Information" %}</h4></td></tr>
    <tr><td><label for="id_addressee">{% trans "Addressee Full Name" %}{% if form.addressee_name.field.required %}*{% endif %}</label></td><td> {{ form.addressee_name }}</td></tr>
   {% if form.addressee_name.errors %}<tr><td>&nbsp;</td><td>*** {{ form.addressee_name.errors|join:", " }}</td></tr>{% endif %}

    <tr><td><label for="id_description">{% trans "Address Description" %}{% if form.description.field.required %}*{% endif %}</label></td><td> {{ form.description }}</td></tr>
   {% if form.description.errors %}<tr><td>&nbsp;</td><td>*** {{ form.description.errors|join:", " }}</td></tr>{% endif %}

 <tr><td><label for="id_street1">{% trans "Street" %}{% if form.street1.field.required %}*{% endif %}</label></td><td> {{ form.street1 }}</td></tr>
    {% if form.street1.errors %}<tr><td class="error" colspan="2">*** {{ form.street1.errors|join:", " }}</td></tr>{% endif %}

    <tr><td><label for="id_street2">{% trans "Street" %}</label></td><td> {{ form.street2 }}</td></tr>
    {% if form.street2.errors %}<tr><td class="error" colspan="2">*** {{ form.street2.errors|join:", " }}</td></tr>{% endif %}

    <tr><td><label for="id_city">{% trans "City" %}{% if form.city.field.required %}*{% endif %}</label></td><td> {{ form.city }}</td></tr>
    {% if form.city.errors %}<tr><td class="error" colspan="2">*** {{ form.city.errors|join:", " }}</td></tr>{% endif %}

    {% if country %}
      {% if form.fields.state.choices %}
      <tr>
        <td><label for="id_state">{% if country.get_admin_area_display %}{{ country.get_admin_area_display }}{% else %}{% trans "State/Province" %}{% endif %} {% if form.state.field.required %}*{% endif %}</label></td>
        <td><p id="id_state_loading" style="display: none">Loading...</p> {{ form.state }}</td>
      </tr>
      {% endif %}
    {% else %}
      <tr>
        <td><label for="id_state">{% trans "State/Province" %} {% if form.state.field.required %}*{% endif %}</label></td>
        <td><p id="id_state_loading" style="display: none">Loading...</p> {{ form.state }}</td>
      </tr>
    {% endif %}
    {% if form.state.errors %}<tr><td class="error" colspan="2">*** {{ form.state.errors|join:", " }}</td></tr>{% endif %}

    <tr><td><label for="id_postal_code">{% trans "Zipcode/Postcode" %}{% if form.postal_code.field.required %}*{% endif %}</label></td><td> {{ form.postal_code }}</td></tr>
    {% if form.postal_code.errors %}<tr><td class="error" colspan="2">*** {{ form.postal_code.errors|join:", " }}</td></tr>{% endif %}

    {% if not country %}
    <tr><td><label for="id_country">{% trans "Country" %}</label></td><td> {{ form.country }}</td></tr>
    {% if form.country.errors %}<tr><td class="error" colspan="2">*** {{ form.country.errors|join:", " }}</td></tr>{% endif %}
    {% endif %}

{% if editing %}
    <tr><td></td><td><input type="submit" value="{% trans "Update" %}"/></td></tr>
{% else %}
    <tr><td></td><td><input type="submit" value="{% trans "Save" %}"/></td></tr>
{% endif %}
</table>
</form>
{% endblock %}

cocom_site/templates/contact/address_form_delete.html
{% extends "shop/base.html" %}
{% load satchmo_contact %}
{% load i18n %}

{% block navbar %}
   <li class="first"><a href="{{ shop_base }}/">{% trans "Home" %}</a></li>
   <li><a href="{% url "satchmo_account_info" %}">{% trans "Account" %}</a></li>
   <li>{% trans "Add Address" %}</li>
{% endblock %}


{% block content %}
<h4>{% trans "Delete address book entry" %}</h4>

<ul class="profile">
    {% addressblock entry %}
<form method="post" action="{% url "satchmo_address_delete" entry.id %}">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="{% trans "Delete" %}"/>
</ul>
</form>
{% endblock %}